spring:
  application:
    name: alexsis
  jpa:
    hibernate:
      ddl-auto: none
#      here we disable hibernate from automatically creating tables, we will do it manually
# st: disable default error page to allow custom exception handlers
  error:
    include-message: always
    include-binding-errors: always
server:
  error:
    whitelabel:
      enabled: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:900000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

#  cloudinary:
Cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:df1wxfrxu}
  api-key: ${CLOUDINARY_API_KEY:999374551769874}
  api-secret: ${CLOUDINARY_API_SECRET:gDjccvOfg_fsnAoRid2U__dq1oA}

# open ai
gemini:
  api:
    key: ${OPENAI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
#    url: https://api.openai.com/v1/chat/completions
    model: gpt-4o-mini
    timeout: 10s

kafka:
  bootstrap-servers: kafka:29092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
#  logging:
#    level:
#      org.springframework.web: DEBUG
#      org.springframework.web.servlet.DispatcherServlet: DEBUG
#      org.springframework.security: DEBUG
